* orgmode-code-extractor
  Orgmode-code-extractor takes as a parameter your orgmode file, and optionally a target directory, and will
  spit out the extracted code in your code blocks using the name of 
  #+BEGIN_SRC
    #+name:
  #+END_SRC
  
  with the extension of the first word following the #+BEGIN_SRC.
  For example, if you have in your org file:
  #+BEGIN_SRC example
    #+name: Creepy.people
    #+BEGIN_SRC javascript
      {
        "name": "Herman Munster",
        "address": "2121 Mockingbird Lane"
      }
    #-END_SRC
  #+END_SRC
  Then a file with the name of "Creepy.people.javascript" with the contents of:
  #+BEGIN_SRC javascript
      {
        "name": "Herman Munster",
        "address": "2121 Mockingbird Lane"
      }
  #+END_SRC
  will be created.
** Installation  
   Installation is accomplished by doing:
   #+BEGIN_SRC commandline
     gem install orgmode-code-extractor
   #+END_SRC
** Contributing to orgmode-code-extractor 
+ Check out the latest master to make sure the feature hasn't been implemented or the bug hasn't been fixed yet.
+ Check out the issue tracker to make sure someone already hasn't requested it and/or contributed it.
+ Fork the project.
+ Start a feature/bugfix branch.
+ Commit and push until you are happy with your contribution.
+ Make sure to add tests for it. This is important so I don't break it in a future version unintentionally.
+ Please try not to mess with the Rakefile, version, or history. If you want to have your own version, or is otherwise necessary, that is fine, but please isolate to its own commit so I can cherry-pick around it.

== Copyright

Copyright (c) 2015 Fred Mitchell. See LICENSE.txt for
further details.

